# -*- coding: utf-8 -*-
"""
エラーコードの定義格納ファイル
コマンド毎に３桁目を変える。
また変数名のpostfixとして、ERROR/WARNING/OKのどれかをつける。
"""

"""
共通
"""
UNKNOWN_ERROR = "E001"
REQUEST_FORMAT_ERROR = "E002"

"""
チャット要求メッセージ保存コマンド
"""
SAVE_MESSAGE_OK = "N100"
SAVE_MESSAGE_LOCKED_ERROR = "E130"

"""
応答メッセージ取得コマンド用
"""
RESPONSE_MESSAGE_OK = "N300"
RESPONSE_LOCKED_WARNING = "W301"
SPECIFIED_MSGID_NOTEXIST_WARNING = "W302"
SPECIFIED_RESID_SEPNO_NOTEXIST_WARNING = "W303"
RESPONSE_FILE_NOTEXIST_WARNING = "W304"

SPECIFIED_MSGID_MULTIPLE_ERROR = "E330"
SPECIFIED_RESID_SEPNO_MULTIPLE_ERROR = "E331"

"""
ログ取得用コマンド
"""
GETLOG_OK = "N500"
GETLOG_NO_SPECIFIED_LOGFILE = "W501"
GETLOG_NO_LOG_KEYWORD_OR_DATETIME = "W502"

"""
チャット状態取得用コマンド
"""
GETSTATUS_OK = "N700"

"""
プロセス起動コマンド
"""
BOOTPROC_OK = "N900"
BOOTPROC_NG = "E901"
